server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pm
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  main:
    web-application-type: servlet